### ISSUE TITLE
Help needed..

### ISSUE THREAD

**Issue by SussyBob** [LambdAurora/LambDynamicLights#249] opened 2024-11-12 14:19 UTC
**Describe the bug**
Minecraft won't start because it ask for Fabric Loader 0.16.5

**Desktop (please complete the following information):**
 - OS: Windows
 - Minecraft 1.21.1
 - Fabric Loader version (currently using Quilt Fabric API 11.0.0-alpha.3+0.102.0-1.21)
 - Mods (Too many)
 - Version 3.1.2+1.21.1
 - Branch 1.21.1

**Additional context**
Here's the logs: https://mclo.gs/RERuZZw

**Comment by LambdAurora** [comment] 2024-11-12 21:22
Duplicate of #246.

Please update to the latest Quilt Loader (including beta versions), if it still does not work please report this to Quilt directly.

**Closed as not planned by LambdAurora** 2024-11-12 21:22 UTC
Labels: bug, duplicate, wontfix
