### ISSUE TITLE
Dynamic lights does not work when item held

### ISSUE THREAD

**Issue by Stupi-001** [LambdAurora/LambDynamicLights#179] opened 2023-08-14 18:30 UTC
I want to make a Modpack and I installed the mod. when I loaded into a world it did not do the dynamic lightning thing around held or thrown items. Í use some other mods Like CIT Sodium and other performance boosting mods

**Comment by lever1209** [comment] 2023-08-15 01:49
with the following mods using lwjgl 3.3.1, minecraft 1.20.1, fabric mappings 1.20.1, loader 0.14.22, and on a completely fresh instance i can reliably re create the above issue
- [Fabric API](https://modrinth.com/mod/P7dR8mSH) [all from 0.83.1+1.20.1 to 0.87.0+1.20.1]
- [LambDynamicLights](https://modrinth.com/mod/yBW8D80W) [2.3.1+1.20.1]

note: the lighting still works on the player model and hand model when thrown and held

**Comment by ytrbqdkflbvbhy** [comment] 2023-08-15 21:17
Same problem, after updating to sodium 0.5.1 and updating all dependent mods, including LambDynamicLights, this issue has occured

**Comment by D4vidPgc** [comment] 2023-08-16 11:22
Same here, but it only lights up entities. If I walk towards mobs I can see them, but blocks are dark. If I drop the item, only the item itself, items around it, mobs and placed entities are illuminated, but no placed blocks.

**Comment by LambdAurora** [comment] 2023-08-16 13:06
Duplicate of #172 and #175.

**Closed as not planned by LambdAurora** 2023-08-16 13:06 UTC
Labels: bug, duplicate, sodium
