### ISSUE TITLE
Crashes when saving world.

### ISSUE THREAD

**Issue by MarinaMarissa** [LambdAurora/LambDynamicLights#41] opened 2020-11-28 03:32 UTC
**Describe the bug**
Crashes when saving world.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - Minecraft [1.16.4]
 - Fabric Loader version [Fabric Loader 0.10.8]
 - Mods [LambDynamicLights 1.3.2+1.16.4, VoxelMap 1.10.13, Fabric API 0.25.1+build.416-1.16]
 - Version [1.3.2]
 - Branch [e.g. mc1.16]

**Additional context**
crash report:[crash-2020-11-28_11.26.06-client.txt](https://github.com/LambdAurora/LambDynamicLights/files/5610005/crash-2020-11-28_11.26.06-client.txt)

**Comment by jessiewestlake** [comment] 2020-12-05 18:50
This same crash happens often when leaving a multiplayer server. I think it is actually VoxelMap which is causing the crash, but it is doing so because of some interaction with LambDynamicLights.

**Comment by LambdAurora** [comment] 2020-12-05 19:08
This is a known issue, I hadn't have time to fix this yet.

**Comment by SirPopa** [comment] 2021-01-06 13:01
I had the same happen to me. Doesn't crash for me when not holding a dynamic light source, everytime I hold a torch and quit the game, game crashes. Might be a conflict with dynamic sound filters as it doesn't seem to happen when I don't have it.

Just wanted to provide a crash report in case it helps:
[crash-2021-01-06_14.52.46-client.txt](https://github.com/LambdAurora/LambDynamicLights/files/5775879/crash-2021-01-06_14.52.46-client.txt)

To Reproduce
Steps to reproduce the behavior:
1. Hold torch in hand
2. Save and quit world

**Comment by LambdAurora** [comment] 2021-01-16 23:35
Fixed in 1.3.3.

**Closed as completed by LambdAurora** 2021-01-16 23:35 UTC
Labels: bug
