### ISSUE TITLE
Glowsquids Glow goes through walls

### ISSUE THREAD

**Issue by Grisu-FTP** [LambdAurora/LambDynamicLights#125] opened 2022-10-21 15:18 UTC
**Describe the bug**
The Glowsquid Glows through walls

**To Reproduce**
1. build a wall between the glowsquid and another wall
2. Enjoy the invisible light source

**Expected behavior**
The light to be cut off and not shine through walls

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch Linux with KDE Plasma on Multimc
 - Minecraft: 1.19.2 quilt
 - Fabric Loader version: Quilt loader 0.17.4
 - Mods: Advancementinfo, appleskin-fabric-mc1.19-2.4.1, architectury-6.2.46-fabric, BetterF3-1.3.2-Forge-1.19, dynamic-fps-2.2.0, enhancedblockentities-0.7.1+1.19, lambdynamiclights-2.1.2+1.19, ferritecore-5.0.1-forge, blur-2.6.0, lithium-fabric-mc1.19.2-0.8.3, moreculling-1.19.1-0.10.0, no-telemetry-1.4.0, NoChatReports-FABRIC-1.19.2-v1.13.5, notenoughcrashes-4.1.8+1.19.2-fabric, phosphor-fabric-mc1.19.x-0.8.1, quilted-fabric-api-4.0.0-beta.13+0.62.0-1.19.2, SimpleRPC-fabric-1.19-3.1.1, sodium-extra-0.4.11+mc1.19.2-build.68, sodium-fabric-mc1.19.2-0.4.4+build.18, technomodel-1.0.2, tooltipsplus-1.3.0+1.19
 
 All of these mods were downloaded from modrinth
 
Screenshot from my private server running on paper:
![image](https://user-images.githubusercontent.com/69594916/197230442-e35d8f3b-946f-4308-a19a-eb6158b82e08.png)
This stripmine is not lit up when the squid is not there

**Comment by LambdAurora** [comment] 2022-10-21 17:59
This is a duplicate of #58.

Fixing this requires a huge performance trade-off.

**Closed as not planned by LambdAurora** 2022-10-21 17:59 UTC
Labels: bug, duplicate, wontfix
