### ISSUE TITLE
Light doesn't go away when a light source isn't held or picked up.

### ISSUE THREAD

**Issue by LorneTheine** [LambdAurora/LambDynamicLights#47] opened 2021-01-18 09:11 UTC
**Describe the bug**
Light doesn't go away and sticks to its last position when a light source is either not held or when it's picked up.

**To Reproduce**
No steps to reproduce the bug, it just suddenly happened. Even when restarting Minecraft, the bug is still there.

**[Video](https://user-images.githubusercontent.com/65266278/104892949-c7216180-59ad-11eb-862a-2d627bfa8d38.mp4)**

**Desktop:**
 - OS: Windows 10 Home
 - Minecraft 1.16.5
 - Fabric Loader version [0.11.1-1.16.5]
 - Mods:
   - DynamicSoundFilters-1.1.3+1.16.2
   - fabric-api-0.29.3+1.16
   - lambdynamiclights-fabric-1.3.3+1.16
   - logical_zoom-0.0.7
   - Mambience-2.1.0+1.16.2
   - phosphor-fabric-mc1.16.4-0.6.0+build.7
   - sodium-fabric-mc1.16.4-0.1.0
 - Version [1.3.3]
 - Branch [mc1.16]

**Additional PC Info (In case there's something important here)**
 - CPU: Intel Core i3-2350M @ 2.30GHz
 - GPU: Intel HD Graphics 3000
 - OpenGL Version: 3.1.0
 - DirectX Version: 10.1
 - RAM: 6gb

Sorry if there are miscommunications, English isn't my native language.

**Comment by F1rz-L** [comment] 2021-01-18 13:36
this happens for me too, basically the light doesnt go away after a "dynamic light item" picked up or isnt held anymore. This only happens for me in this update.

**Comment by LambdAurora** [comment] 2021-01-18 15:48
Fixed in version [1.3.4](https://modrinth.com/mod/yBW8D80W/version/hKXQNf9z).

The bug was caused by the fact that `ChunkSectionPos` and `BlockPos` packing methods are not the same.

**Closed as completed by LambdAurora** 2021-01-18 15:48 UTC
Labels: bug
